name: "Build Release"
on:
  release:
    types: [published]
jobs:
  build:
    name: "Build Release"
    runs-on: macos-latest
    steps:

    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup node"
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: "Build"
      run: |
        yarn
        yarn make

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: out/**/*.zip
